# Generated by Django 5.0.6 on 2024-07-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
