# Generated by Django 5.0.6 on 2024-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp2', '0002_remove_users_phonenumber_users_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
